<a href="https://colab.research.google.com/github/barabonda/SK-AI-FLY/blob/main/4%EC%A3%BC%EC%B0%A8example_policy_eval_gridworld.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The Simple Gridworld Problem

In [ ]:
import numpy as np

P = np.array([
    # up
    [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]],

    # down
    [[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]],

    # left
    [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]],

    # right
    [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]], dtype='float32')

P.shape

(4, 15, 15)

In [ ]:
P = P.transpose(1, 0, 2)

In [ ]:
P.shape

(15, 4, 15)

In [ ]:
R = np.array([
    [-1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0], # up
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1,  0], # down
    [ 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0], # left
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  0]], #right
    dtype='float32')

In [ ]:
R.shape

(4, 15)

In [ ]:
R = R.transpose()

In [ ]:
R.shape

(15, 4)

In [ ]:
pi = np.ones((15, 4), dtype='float32') * 0.25

In [ ]:
pi.shape

(15, 4)

In [ ]:
def policy_eval(P, R, pi, maxiter=30):
    V = np.zeros((maxiter, 15), dtype='float32')

    for i in range(maxiter-1):
        V[i+1] = np.squeeze(
            np.matmul(
                np.expand_dims( pi, 1 ),
                np.expand_dims( R + 0.6 * np.dot(P, V[i]), 2 )))

    return V[maxiter-1]

def policy_upd(P, R, v):
    a_idx = np.argmax(np.squeeze(np.expand_dims( R + 0.6 * np.dot(P, v), 2 )), axis=1)
    pi = np.zeros((15, 4), dtype='float32')
    pi[range(15), a_idx] = 1.
    return pi

pi_old = None
pi = np.ones((15, 4), dtype='float32') * 0.25

while not np.all(np.equal(pi_old, pi)):
    pi_old = pi.copy()
    v = policy_eval(P, R, pi)
    pi = policy_upd(P, R, v)

print("The optimal policy is:\n", pi)

ValueError: shapes (16,16) and (15,) not aligned: 16 (dim 1) != 15 (dim 0)

### In summary,

In [ ]:
def policy_eval(P, R, pi, maxiter=30):
    V = np.zeros((maxiter, 15), dtype='float32')

    for i in range(maxiter-1):
        V[i+1] = np.squeeze(
            np.matmul(
                np.expand_dims( pi, 1 ),
                np.expand_dims( R + 0.6 * np.dot(P, V[i]), 2 )))

    return V[maxiter-1]

def policy_upd(P, R, v):
    print(np.squeeze(np.expand_dims( R + 0.6 * np.dot(P, v), 2 )))
    a_idx = np.argmax(np.squeeze(np.expand_dims( R + 0.6 * np.dot(P, v), 2 )), axis=1)
    pi = np.zeros((15, 4), dtype='float32')
    pi[range(15), a_idx] = 1.
    return pi

pi_old = None
pi = np.ones((15, 4), dtype='float32') * 0.25

while not np.all(np.equal(pi_old, pi)):
    pi_old = pi.copy()
    v = policy_eval(P, R, pi)
    pi = policy_upd(P, R, v)

print(pi)

[[-1.8125088 -2.258132   1.        -2.346084 ]
 [-2.346084  -2.381265  -1.8125088 -2.434036 ]
 [-2.434036  -2.346084  -2.346084  -2.434036 ]
 [ 1.        -2.346084  -1.8125088 -2.258132 ]
 [-1.8125088 -2.381265  -1.8125088 -2.381265 ]
 [-2.346084  -2.258132  -2.258132  -2.346084 ]
 [-2.434036  -1.8125088 -2.381265  -2.346084 ]
 [-1.8125088 -2.434036  -2.346084  -2.381265 ]
 [-2.258132  -2.346084  -2.346084  -2.258132 ]
 [-2.381265  -1.8125088 -2.381265  -1.8125088]
 [-2.346084   1.        -2.258132  -1.8125088]
 [-2.346084  -2.434036  -2.434036  -2.346084 ]
 [-2.381265  -2.346084  -2.434036  -1.8125088]
 [-2.258132  -1.8125088 -2.346084   1.       ]
 [ 0.         0.         0.         0.       ]]
[[-0.39999998 -1.24        1.         -1.24      ]
 [-1.24       -1.744      -0.39999998 -1.744     ]
 [-1.744      -1.24       -1.24       -1.744     ]
 [ 1.         -1.24       -0.39999998 -1.24      ]
 [-0.39999998 -1.744      -0.39999998 -1.744     ]
 [-1.24       -1.24       -1.24       -

In [ ]:
import numpy as np

# Define the transition probability matrix P for a deterministic grid world
# (assuming that the agent always reaches the intended cell)
P = np.eye(16)

# Define the reward matrix R
# R[s, a] is the reward for taking action a in state s
R = np.zeros((16, 4), dtype='float32')

# Define the blocked cells
blocked_cells = [1, 5, 6, 10]

# Set rewards for valid actions (up, down, left, right)
for s in range(16):
    if s not in blocked_cells:
        # Up
        R[s, 0] = -1 if s - 4 < 0 or (s - 4) in blocked_cells else 0
        # Down
        R[s, 1] = -1 if s + 4 > 15 or (s + 4) in blocked_cells else 0
        # Left
        R[s, 2] = -1 if s % 4 == 0 or (s - 1) in blocked_cells else 0
        # Right
        R[s, 3] = -1 if (s + 1) % 4 == 0 or (s + 1) in blocked_cells else 0

# Function for policy evaluation
def policy_eval(P, R, pi, maxiter=30):
    V = np.zeros((maxiter, 16), dtype='float32')

    for i in range(maxiter-1):
        V[i+1] = np.squeeze(
            np.matmul(
                np.expand_dims(pi, 1),
                np.expand_dims(R + 0.6 * np.dot(P, V[i]), 2)))

    return V[maxiter-1]

# Function for policy update
def policy_upd(P, R, v):
    # Set the policy to 0 for blocked cells
    R_blocked = np.copy(R)
    R_blocked[:, :] = -np.inf
    for blocked_cell in blocked_cells:
        R_blocked[blocked_cell, :] = 0

    a_idx = np.argmax(np.squeeze(np.expand_dims(R_blocked + 0.6 * np.dot(P, v), 2)), axis=1)
    pi = np.zeros((16, 4), dtype='float32')
    pi[range(16), a_idx] = 1.
    return pi

# Initial policy
pi_old = None
pi = np.ones((16, 4), dtype='float32') * 0.25

# Policy iteration loop
while not np.all(np.equal(pi_old, pi)):
    pi_old = pi.copy()
    v = policy_eval(P, R, pi)
    pi = policy_upd(P, R, v)

# Display the final policy
print(pi)


ValueError: operands could not be broadcast together with shapes (16,4) (16,) 

In [ ]:
def find_path(grid, start, goal):
    queue = [(start, [start])]
    visited = set()

    while queue:
        (current, path) = queue.pop(0)
        if current in visited:
            continue

        visited.add(current)

        for direction in [(1, 0), (-1, 0), (0, 1), (0, -1)]:
            next_step = (current[0] + direction[0], current[1] + direction[1])

            if (
                0 <= next_step[0] < len(grid) and
                0 <= next_step[1] < len(grid[0]) and
                grid[next_step[0]][next_step[1]] != -1
            ):
                new_path = list(path)
                new_path.append(next_step)

                if grid[next_step[0]][next_step[1]] == goal:
                    return new_path

                queue.append((next_step, new_path))

# Example usage
grid = [
    [  0,1,2,3],
    [4, -11,-11,-11],
    [5,6,-11,11]
    ,[7,8,9,10]
]

print(find_path(grid=grid,start=(0,0),goal=11))


[(0, 0), (1, 0), (2, 0), (2, 1), (2, 2), (2, 3)]


In [ ]:
import numpy as np

P = np.array([
    # up
    [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]],

    # down
    [[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]],

    # left
    [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]],

    # right
    [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]], dtype='float32')

P.shape
P = P.transpose(1, 0, 2)
R = np.array([
    [-1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0], # up
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1,  0], # down
    [ 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0], # left
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  0]], #right
    dtype='float32')
R = R.transpose()
pi = np.ones((15, 4), dtype='float32') * 0.25
def policy_eval(P, R, pi, maxiter=30):
    V = np.zeros((maxiter, 15), dtype='float32')

    for i in range(maxiter-1):
        V[i+1] = np.squeeze(
            np.matmul(
                np.expand_dims( pi, 1 ),
                np.expand_dims( R + 0.6 * np.dot(P, V[i]), 2 )))

    return V[maxiter-1]

def policy_upd(P, R, v):
    a_idx = np.argmax(np.squeeze(np.expand_dims( R + 0.6 * np.dot(P, v), 2 )), axis=1)
    pi = np.zeros((15, 4), dtype='float32')
    pi[range(15), a_idx] = 1.
    return pi

pi_old = None
pi = np.ones((15, 4), dtype='float32') * 0.25

while not np.all(np.equal(pi_old, pi)):
    pi_old = pi.copy()
    v = policy_eval(P, R, pi)
    pi = policy_upd(P, R, v)

print("The optimal policy is:\n", pi)

The optimal policy is:
 [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]


In [ ]:
# Path finding

import numpy as np
P = np.array([
# up
[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]],
# down
[[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]],
# left
[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]],
# right
[[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]], dtype='float32')
P.shape


P.shape
P = P.transpose(1, 0, 2)
R = np.array([
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 0], # up
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0], # down
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0], # left
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0]], #right

    dtype='float32')
R = R.transpose()
grid = [
    [  0,1,2,3],
    [4, -11,-11,-11],
    [5,6,-11,11]
    ,[7,8,9,10]
]
# 4번째 행의 3번째 열을 -11로 바꿔주세요.
grid[3][2] = -11
pi = np.ones((12, 4), dtype='float32') * 0.25
def policy_eval(P, R, pi, maxiter=30):
    V = np.zeros((maxiter, 12), dtype='float32')

    for i in range(maxiter-1):
        V[i+1] = np.squeeze(
            np.matmul(
                np.expand_dims( pi, 1 ),
                np.expand_dims( R + 0.6 * np.dot(P, V[i]), 2 )))

    return V[maxiter-1]

def policy_upd(P, R, v):
    a_idx = np.argmax(np.squeeze(np.expand_dims( R + 0.6 * np.dot(P, v), 2 )), axis=1)
    pi = np.zeros((12, 4), dtype='float32')
    pi[range(12), a_idx] = 1.
    return pi

pi_old = None
pi = np.ones((12, 4), dtype='float32') * 0.25

while not np.all(np.equal(pi_old, pi)):
    pi_old = pi.copy()
    v = policy_eval(P, R, pi)
    pi = policy_upd(P, R, v)

print("The optimal policy is:\n", pi)

The optimal policy is:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [ ]:
import numpy as np

P = np.array([
    [0.5, 0.5, 0, 0],
    [0.5, 0, 0.5, 0],
    [0, 0.5, 0, 0.5],
    [0, 0, 0.5, 0.5]
])

R = np.array([
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 1]
])

def policy_eval(P, R, pi, maxiter=30):
    V = np.zeros((maxiter, 4), dtype='float32')

    for i in range(maxiter-1):
        V[i+1] = np.squeeze(
            np.matmul(
                np.expand_dims( pi, 1 ),
                np.expand_dims( R + 0.6 * np.dot(P, V[i]), 2 )))

    return V[maxiter-1]

def policy_upd(P, R, v):
    a_idx = np.argmax(np.squeeze(np.expand_dims( R + 0.6 * np.dot(P, v), 2 )), axis=1)
    pi = np.zeros((4, 4), dtype='float32')
    pi[range(4), a_idx] = 1.
    return pi

pi_old = None
pi = np.ones((4, 4), dtype='float32') * 0.25

while not np.all(np.equal(pi_old, pi)):
    pi_old = pi.copy()
    v = policy_eval(P, R, pi)
    pi = policy_upd(P, R, v)

print("최적의 정책은 다음과 같습니다:\n", pi)

최적의 정책은 다음과 같습니다:
 [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#e- soft Greedy Policy

import random
epsilon = 0.01
def get_eps_soft_action(step):
  assert(step['observation'][0] >= 12 and step['observation'][0] <= 21)
  observ = step['observation']
  idx = (observ[0] - 12, observ[1] - 1, observ[2])

  if random.random() < epsilon:
    return 1 if Q[idx][0] > Q[idx][1] else 0
  else:
    return 1 if Q [idx][0] < Q[idx][1] else 0

In [ ]:
def generate_episode():
  episode = list()
  actions = list()
  step = generate_start_step()
  episode.append(step)

  while step['step_type']!=STEPTYPE_LAST:
    action = get_eps_soft_action(step)
    step = generate_next_step(step, action)
    episode.append(step)
    actions.append(action)
  return episode, actions


In [ ]:
def in_episode(epi, observ,action):
  for s, a in zip(*epi):
    if s['observation'] == observ and a == action:
      return True
  return False

In [ ]:
#recall the MC Prediction Algorithm
maxiter = 1000000
gamma = 1
epsilon = 0.4

N = np.zeros((10,10,2,2),dtype = 'float32')
SUM = np.zeros((10,10,2,2), dtype = 'float32')
Q = np.random.uniform(size = (10,10,2,2))

for _ in range(maxiter):
  episode = generate_episode()
  G = 0
  last_step = episode[0]
  while len(episode[0])>0:
    G = gamma*G + last_step['reward']
    last_step = episode[0].pop()
    last_action = episode[1].pop()
    observ = last_step['observation']
    idx = (observ[0] - 12, observ[1] - 1, observ[2], last_action)
    if not in_episode(episode, observ, last_action):
      N[idx] += 1
      SUM[idx] += G
      Q[idx] = SUM